### ISSUE TITLE
Webpack compatible

### ISSUE THREAD

**Issue by blackChef** [espadrine/localeval#7]
`var node_js = typeof exports === 'object';`
Currently, detection is done by checking if cmd is supported. However, when using webpack or other frontend build tools, cmd is also supported.

I found this [stackoverflow question](http://stackoverflow.com/questions/4224606/how-to-check-whether-a-script-is-running-under-node-js) . Hope it's helpful.

**Comment by espadrine** [comment]
I believe it has been fixed by 0b26896b0.

Thank you for reporting.
